# Generated by Django 3.2.9 on 2021-11-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='gener',
            new_name='gender',
        ),
    ]
