# Generated by Django 3.2.9 on 2021-11-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20211113_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='challenge_history',
            new_name='challengeHistory',
        ),
    ]
