# Generated by Django 3.2.9 on 2021-11-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_rename_challenge_history_challengehistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
