# Generated by Django 3.2.9 on 2021-11-14 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20211113_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='challengeHistory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('challenge_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.challenges')),
                ('user_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.users')),
            ],
        ),
    ]
