# Generated by Django 3.2.9 on 2021-11-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_challengehistory2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='id',
        ),
        migrations.AlterField(
            model_name='challenges',
            name='challenge_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='challengehistory',
            table='challengeHistory',
        ),
        migrations.AlterModelTable(
            name='challenges',
            table='challenges',
        ),
        migrations.AlterModelTable(
            name='friends',
            table='friends',
        ),
        migrations.AlterModelTable(
            name='goals',
            table='goals',
        ),
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
        migrations.AlterModelTable(
            name='tasks',
            table='tasks',
        ),
        migrations.AlterModelTable(
            name='usergoals',
            table='userGoals',
        ),
        migrations.DeleteModel(
            name='challengeHistory2',
        ),
    ]
